### ISSUE TITLE
Doesn't build on NG

### ISSUE THREAD

**Issue by DruggedBunny** [maxmods/ifsogui.mod#1]
Hi Brucey, quick summary is that ifsogui.mod builds fine on bmx152, but fails with ng.

I've updated `ifsogui.mod/gui.mod/zipstream/bufferedstream.bmx` so it builds (the first hurdle) -- copy [here](https://gist.github.com/DruggedBunny/8debc3a6af13e83d2247cb069cf161be) -- but it then fails while building (or linking?) ifsogui.mod/listbox.mod, with multiple instances of:

> ifsogui.mod/listbox.mod/.bmx/listbox.bmx.release.win32.x86.c:832:6: error: redefinition of 'ifsogui_listbox_ifsoGUI_ListBox_FastQuickSort_v_aTifsoGUI_ListItem_QuickSort_v_aTifsoGUI_ListItemii'

I've completely rebuilt bmx-ng and modules from scratch via Frisky (thinking it might have been a MinGW compatibility thing -- all is being built with the one version though!), copied in a fresh ifsogui.mod with my bufferedstream fixes, but still end up with this result.

I assume something in the generated C++ is repeated for some reason... ?

I don't think it's ever worked with NG, but would be nice to have... I'm specifically getting this build error while trying to build [this openb3d example](https://github.com/DruggedBunny/openb3d.mod/blob/master/openb3d.mod/examples/ifsogui/combobox.bmx), which works in 'vanilla'.

If nothing else, it's an example of valid code that works in vanilla but not NG... :P

**Comment by woollybah** [comment]
Should be working now
